import type { Metadata } from "next";
import { Inter, Lekton } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { lekton } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lekton.className} py-2`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
