"use client";
import type { Metadata } from "next";
import { Inter, Lekton } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { lekton } from "./fonts";
import { Provider } from "@/components/providers/Provider";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="overflow-x-visible overflow-y-auto"
      suppressHydrationWarning
    >
      <body
        className={`${lekton.className} py-2 overflow-x-visible overflow-y-auto`}
      >
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
