import type { Metadata } from "next";
import { Lekton } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const lekton = Lekton({
  subsets: ["latin-ext"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lekton.className} py-2`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
